apiVersion: v1
kind: Pod
metadata:
  name: flaskpod
  labels:
    app: flaskapp 
spec:
  containers:
  - name: flask
    image: jungch15/flaskapp:v1.0.0
    ports:
    - containerPort: 5000
  imagePullSecrets:
    - name: myregistrykey

